[build]
  command = "gatsby build"
  publish = "public/"
  functions = "functions/"
[dev]
  command = "gatsby develop"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# Asset optimization
#[build.processing]
#  skip_processing = false
#[build.processing.css]
#  bundle = true
#  minify = true
#[build.processing.js]
#  bundle = true
#  minify = true