[build]
  command = "gatsby build"
  publish = "public/"
  functions = "functions/"
[dev]
  command = "gatsby develop"

[[headers]]
  for = "https://www.dev.faiqnaufal.com/*"
  [headers.values]
    X-Robots-Tag = "noindex"

  for = "https://dev-faiqnaufal.netlify.app/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true